### ISSUE TITLE
To host on github pages, you need not to keep this name.

### ISSUE THREAD

**Issue by zaidajani** [solomonshalom/solomonshalom.github.io#1]
### You need not to keep 'solomonshalom.github.io` as repo name in order to host.

As per your repo name, it seems that you want to host 'solomonshalom', so just change the repo name to solomonshalom, and then get on to repository settings and do the following. 

1. hop on to settings

![image](https://user-images.githubusercontent.com/55057446/131460372-412545e3-a089-4c74-b5bc-237a230e4731.png)

2. then just enable GitHub pages as shown in the image above. ( on the image, Github pages is enabled ).

Then your page would be hosted.

I know that your page is hosted, but this is just a suggestion in order to simplify the work process.

**Comment by solomonshalom** [comment]
Hey, thanks for the suggestion. The reason is that I need to add a domain name, not through DNS/Nameserver but instead like a redirect. This is why, I kept the name

**Comment by zaidajani** [comment]
Ok, BTW, great theme.
